version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/src
    ports:
      - 8000:8000
    tty: true

  db:
    build: ./db/
    env_file:
      - ./db/.env
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
