"""first migration

Revision ID: 879813fc7126
Revises: 
Create Date: 2022-05-14 10:17:54.202996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879813fc7126'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
